version: "3.8"
volumes:
  lastfm:
  mb:

services:
  musicbrainz:
    build:
      context: ./mbiz
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-14}
        - MBID_TOKEN=${MBID_TOKEN}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so"
    shm_size: "2GB"
    volumes:
      - mb:/var/lib/postgresql/data
      - type: bind
        source: ./mbiz/create-db.sh
        target: /docker-entrypoint-initdb.d/create-db.sh
      - type: bind
        source: ./model/src/main/resources/db/PostgresBaseline.sql
        target: /docker-entrypoint-initdb.d/PostgresBaseline.sql
    expose:
      - 5432
    ports:
      - "5432:5432"


  lastfm:
    image: "mariadb:latest"
    hostname: lastfm
    env_file:
      - .env
    volumes:
      - ./model/src/main/resources/db/migrations/:/docker-entrypoint-initdb.d
      - lastfm:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    healthcheck:
      test: mysqladmin -p${MARIADB_ROOT_PASSWORD} ping -h localhost
      interval: 2s
      start_period: 5s
      timeout: 10s
      retries: 100

  chuu:
    build: .
    command: dockerize -wait tcp://lastfm:3306 sh -c 'java --enable-preview -jar /app/chuu.jar  stop-asking'
